name: CI

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pxshadow/setup-hashlink@v1.0.2 #hashlink
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.
      - name: Install lix
        run: npm i lix -g
      - name: Run lix
        run: npx lix download
      - name: Build source
        run: npx haxelib dev go2hx .
      - name: Test run
        run: npx haxelib run go2hx ./rnd
      - name: Memory info
        run: free -m
      - name: Run StdGo autogenerator
        run: npx haxe stdgo.hxml
      - name: Build tests
        run: npx haxe tests.hxml
      - name: Run tests
        run: hl tests.hl ci
        env:
          HXCPP_COMPILE_CACHE: ~/hxcppcache
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: StdGo automatic compile