name: CI

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 #nodejs
        with:
          node-version: '14'
      - uses: pxshadow/setup-hashlink@v1.0.1 #hashlink

      - name: install lix
        run: npm i lix -g
      - name: run lix
        run: npx lix download
      - name: build source
        run: npx haxelib dev go2hx .
      - name: test repl
        run: npx haxelib run go2hx
      - name: build tests
        run: npx haxe tests.hxml
        env:
          HXCPP_COMPILE_CACHE: ~/hxcppcache